// sveltblazers/src/routes/game/ChatBox.svelte
<script lang="ts">
	import ChatInput from './ChatInput.svelte';
	import ChatLog from './ChatLog.svelte';
</script>

<div class="chat-box fixed bottom-2 left-2 z-10 w-72 bg-[#221569]">
	<div class="chat-messages h-24 overflow-y-hidden break-words bg-[#221569] text-[#b5e6ff]"></div>
	<ChatLog />
	<hr class="chat-line m-0 border-t border-black" />
	<ChatInput />
</div>

// frontend/src/app/components/ChatBox.tsx
export const ChatBox = () => {
  return (
    <div className="chat-box bg-[#221569] w-72 fixed bottom-2 left-2 z-10">
      <div className="chat-messages text-[#b5e6ff] bg-[#221569] h-24 overflow-y-hidden break-words"></div>
      <hr className="chat-line border-t border-black m-0" />
      <input type="text" className="chat-input bg-[#221569] border-none mt-1 outline-none shadow-none" />
    </div>
  );
};
